# backend:
#   name: github
#   repo: stackrole/gatsby-starter-base
#   commit_messages:
#     create: 'Create {{collection}} “{{slug}}”'
#     update: 'Update {{collection}} “{{slug}}”'
#     delete: 'Delete {{collection}} “{{slug}}”'
#     uploadMedia: '[skip ci] Upload “{{path}}”'
#     deleteMedia: '[skip ci] Delete “{{path}}”'

# for local testing 
backend:
  name: git-gateway
local_backend: true


media_folder: "static/assets" 
public_folder: "/assets" 

collections:
  - name: 'posts' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Posts' # Used in the UI
    label_singular: 'Post' # Used in the UI, ie: "New Post"
    description: >
      Create awesome content here.
    folder: 'src/content/posts'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    summary: '{{title}} — {{year}}/{{month}}/{{day}}'
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: 'Template', name: 'template', widget: 'hidden', default: 'blog-post'}
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - { label: 'Slug', name: 'slug', widget: 'string', hint: 'Start slug with /. Use only alphanumeric characters, - and _. Avoid spaces in any cases.'}
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          dateFormat: 'YYYY-MM-DD',
          timeFormat: 'HH:mm',
          format: 'YYYY-MM-DD HH:mm',
        }
      - { label: 'SEO Description', name: 'description', widget: 'text' }
      - {
          label: 'Featured Image',
          name: 'featuredImage',
          widget: 'image',
          required: false,
          tagname: ''
        }

      - { label: 'Body', name: 'body', widget: 'markdown', hint: 'Main content goes here.' }
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home"
        name: "home"
        file: "src/content/pages/index.md"
        fields:
        - {label: "Template", name: "template", widget: "hidden", default: "index-page" }
        - {label: "Slug", name: "slug", widget: "hidden", default: "/" }
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Tagline", name: "tagline", widget: "string"}
        - {label: "Featured Image", name: "featuredImage", widget: "image"}
        - {label: "Body", name: "body", widget: "markdown"}
        - label: "CTA"
          name: "cta"
          widget: "object"
          fields: 
            - name: "ctaText"
              label: "CTA text"
              widget: "string"
            - name: "ctaLink"
              label: "CTA Link"
              widget: "string"
      - label: "About"
        name: "about"
        file: "src/content/pages/about.md"
        fields:
        - {label: "Template", name: "template", widget: "hidden", default: "about-page" }
        - {label: "Slug", name: "slug", widget: "hidden", default: "/about" }
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Body", name: "body", widget: "markdown"}